### ISSUE TITLE
missing file "OCIM2_CTL_He.mat"

### ISSUE THREAD

**Issue by NirvanaTricho** [zliangocean/Dissolved-organic-phosphorus-concentrations-in-the-surface-ocean-controlled-by-both-phosp#1]
Error in figure1a.m (line 15), Unable to find file or directory 'OCIM2/OCIM2_CTL_He.mat'

How can I get the file?

**Comment by zliangocean** [comment]
> Error in figure1a.m (line 15), Unable to find file or directory 'OCIM2/OCIM2_CTL_He.mat'
> 
> How can I get the file?

Thank you for asking!

I did not put OCIM2 in this repository because 1) OCIM2 is not my product, and 2) this file is too large... (~2 Gb).

OCIM2 is an ocean circulation inverse model (including grids) maintained by Tim DeVries. You can download OCIM2 from his website:

https://tdevries.eri.ucsb.edu/models-and-data-products/

where you can see:

"OCIM2 (DeVries and Holzer, 2019). You may download the OCIM2 circulations [here](https://www.dropbox.com/sh/eun1dkwjeqvax80/AADn1eHdK3oZdKVynZLII2XSa?dl=1) (warning: very large file ~2 GB).  This includes the various different versions of the OCIM2 as outlined in Table 1 of [DeVries and Holzer (2019)](https://www.dropbox.com/s/hs06agkydqumgem/devries_jgr_2019.pdf?dl=1). See DeVries and Holzer (2019) for details on how the model differs from the OCIM1. The scripts above for OCIM1 will also work for OCIM2. If you use these results, cite DeVries and Holzer (2019)."


If you have more questions, let me know

**Comment by NirvanaTricho** [comment]
Thanks for such quick reply! The problem has been solved.

Maybe you should consider updating the code to add the information as comment. Many researchers from other fileds are not familiar with the OCIM.
